### PR TITLE
Added Issue 25: Trivy Information to Apache Superset

### PR DESCRIPTION
**Pull request by AlfredoPardo**
Added script for sending Trivy Information to Apache Superset (PostgreSQL)

### CODE REVIEW

**Comment by itaysk** [comment]
@AlfredoPardo This is going to be an annoying request, but we'll need to rebase each PR after I merge the previous. Since the adjacent line addition create git conflicts, and I can't manually resolve them because the repo source here is "unknown" (perhaps you deleted you fork).
So, can you please rebase this PR on top of master, and we shall do the same with the other PRs after this one is merged.
Sorry for the inconvenience

**Comment by AlfredoPardo** [comment]
Hi Itay,

No problem at all.

I've seen 25 is already in contrib-integrations.md in master. I've created a new branch in my fork and made a new pull-request from there for #26. I'll be trying with new branches leaving them in my repository just in case.

Kind regards,

Alfredo

**Comment by AlfredoPardo** [comment]
There are now 3 new branches in my fork. I'll be looking for your comments to see if this works now.

Thanks again and sorry for the inconvenience.

**Comment by itaysk** [comment]
Thank you, I've merged the other PRs

**Pull request closed without merging**
